### ISSUE TITLE
Todo list [2021.05.13]

### ISSUE THREAD

**Issue by NermanYT** [NermanYT/MoreRedstoneStuffs#1]
- [x] Add Deactivated Redstone 
- [ ] Add Deactivated Redstone texture
- [ ] Compressed Redstone Armor rename to Deactivated Redstone Armor
- [ ] Compressed Redstone Armor crafting recipe change
